### ISSUE TITLE
Hey dude, can i join the development on this project? It seems very interesting for me.

### ISSUE THREAD

**Issue by Lqlsoftware** [nnao45/dntk#1]

**Comment by nnao45** [comment]
@Lqlsoftware 
Hi Lqlsoftware

Awesome!
This is what I have made in killing time, 
but I like this project 😄

Umm...What do you have improve idea?
If you have any idea, I cooperate!

**Comment by nnao45** [comment]
I send Collaborators request.
If you want to Join, Welcome!

**Comment by Lqlsoftware** [comment]
Thanks man!
I think we can add a cursor to the formula's end (like a console waiting for input)
![image](https://user-images.githubusercontent.com/19875776/43883431-af95efdc-9be5-11e8-91cb-13884c4106e7.png)
(I don't know where i'm inputing when the first time I use it.)
And more function and operate are needed, like sqrt(), ^...etc.

**Comment by nnao45** [comment]
@Lqlsoftware 
Thanks!!

open 2 issue.
check it!
#2
#3

**Comment by nnao45** [comment]
Next time, we adjust and develop in the other  issue.
