### ISSUE TITLE
 a cursor to the formula's end (like a console waiting for input)

### ISSUE THREAD

**Issue by nnao45** [nnao45/dntk#2]
![43883431-af95efdc-9be5-11e8-91cb-13884c4106e7](https://user-images.githubusercontent.com/17565502/43893511-31b609d8-9c0a-11e8-8612-90976aced6c7.png)

**Comment by nnao45** [comment]
@Lqlsoftware 
ummmmm....

So, I had thought this problem at the coding,
but I gave up 😩

because I had no idea 😔
I think solving idea this problem, 
we change the shell have "cursor point value"(env?), may be.

I try think to solving this problem!

**Comment by Lqlsoftware** [comment]
@nnao45 
emmmmm....

No no no, we can change the edit cursor like "█" and make it flash per 500ms, like a real cursor.
But it is not working like its gif in my iTerm (Macbook Pro), I need to press enter to see the result.

**Comment by nnao45** [comment]
@Lqlsoftware 

> we can change the edit cursor like "█" and make it flash per 500ms, like a real cursor.

Are you sure? Nice!!😆
Can you push other branch(like develop branch)?

**Comment by nnao45** [comment]
@Lqlsoftware 

So, I found Idea.
This idea from `https://github.com/nsf/termbox-go` 

this terminal library, has `func SetCursor(x, y int) `
this func can set cursor posision when only using termbox-go
https://github.com/nsf/termbox-go/blob/157ff97de075fe3e9e54bda782b8ca6b552dfff7/api.go#L204

And...this func has func, `func write_cursor(x, y int)`.
this func is ...write escape sequence with uint...

```
func write_cursor(x, y int) {
	outbuf.WriteString("\033[")
	outbuf.Write(strconv.AppendUint(intbuf, uint64(y+1), 10))
	outbuf.WriteString(";")
	outbuf.Write(strconv.AppendUint(intbuf, uint64(x+1), 10))
	outbuf.WriteString("H")
}
```

https://github.com/nsf/termbox-go/blob/master/termbox.go#L91

I try and can be applied this solution, imple dntk.

**Comment by Lqlsoftware** [comment]
@nnao45 
Nice idea! So we just need to calculate the position, and make cursor appear.

**Comment by nnao45** [comment]
@Lqlsoftware 
I make PR that This problem is fixed.
Check it #8

**Comment by Lqlsoftware** [comment]
@nnao45 
OK, I will close this issue.
