### ISSUE TITLE
error: environment variable `LINUX_TERM_LIB` not defined

### ISSUE THREAD

**Issue by Matthias-Fauconneau** [nnao45/dntk#23]
error: environment variable `LINUX_TERM_LIB` not defined
 --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/dntk-2.1.18/src/term/mod.rs:5:10

**Comment by nnao45** [comment]
@Matthias-Fauconneau 
Hi
this LINUX_TERM_LIB is only used compile-time in linux 
https://github.com/nnao45/dntk/blob/master/src/term/mod.rs#L5

your environment not musl, try `export LINUX_TERM_LIB=linux_gnu.rs`、
your environment musl, try `export LINUX_TERM_LIB=linux_musl.rs`、
