### ISSUE TITLE
more function and operate are needed, like sqrt(), ^...etc.

### ISSUE THREAD

**Issue by nnao45** [nnao45/dntk#3]

**Comment by nnao45** [comment]
@Lqlsoftware 
^ is impled 😆

https://asciinema.org/a/FKnOPayvPSZLGqujDlg1fARGL

so, `dntk` is impled equal to gnu bc impled.
look here 👉 https://www.gnu.org/software/bc/manual/html_mono/bc.html

but you say sqrt() is no impled at `gnu bc` & `dntk`.
it's challenge!

**Comment by Lqlsoftware** [comment]
@nnao45 
Hahaha, my bad. I didn't notice gnu bc.
