### ISSUE TITLE
Not working like its gif (stdin is not hidden)

### ISSUE THREAD

**Issue by Lqlsoftware** [nnao45/dntk#4]
But it is not working like its gif in my iTerm (Macbook Pro). Stdin is not hidden, so i need to press enter to see the result. Is there a solution or my operation mistake?

**Comment by nnao45** [comment]
!?!??
I use Macbook Pro & iterm2 😳 and recording this env.
umm...

> Stdin is not hidden

Can you recorde and share your problem?
for example, asciinema.
https://asciinema.org

**Comment by Lqlsoftware** [comment]
Hi dude, here are my record by asciinema. (asciinema is a great tool!)
[https://asciinema.org/a/f7o7FHZEiBNVIIa8z2SiRWFxN](https://asciinema.org/a/f7o7FHZEiBNVIIa8z2SiRWFxN)
Is the iterm theme's problem?

**Comment by nnao45** [comment]
Hi @Lqlsoftware 
Yes!! I love asciinema😁

And now, I check your record....wow...unbelivable...😱
But my test, I use "iTerm Build 0.10", but work correctly(like readme gif).

Please Try it!! 

```
$ while : ; do echo -en "\r$(date +%H:%M:%S)" ; sleep 1 ; done 
```

if work correctly(like readme gif), working is like this.
https://asciinema.org/a/gnVIamPw2KXF28ormB2hrZpPq


look problem, I suggest, your terminal `\r` working may be not  correctly.
(\r means ASCii code 0x0D. This code "only" back to the head line. dont move to a newline)

I suggest, It's occred by iterm theme or setting.

**Comment by Lqlsoftware** [comment]
@nnao45 
Dude, my terminal \r works correctly...
here:
[https://asciinema.org/a/vnqPTTNAL1SmpICAsrKYFrocp](https://asciinema.org/a/vnqPTTNAL1SmpICAsrKYFrocp)

I've tried my default console, It is still not working.
Or maybe stdin just cover the stdout, so I cannot see stdout.

**Comment by nnao45** [comment]
@Lqlsoftware 
Thanks your practice.
still...dntk working may be bad.

Please try upgrade dntk.

```
$ brew upgrade nnao45/dntk/dntk
```

or

```
$ wget https://github.com/nnao45/dntk/releases/download/v1.0.9/dntk-darwin-amd64-v1.0.9.tar.gz
$ tar xvfz dntk-darwin-amd64-v1.0.9.tar.gz
```

**Comment by Lqlsoftware** [comment]
@nnao45 
I get! It is the stty problem.
I've tried for using:
`
stty -F /dev/tty cbreak min 1 
stty -F /dev/tty erase \n
stty -F /dev/tty -echo
`
to hidden my input, but it was not working.
So I just try input `stty -F /dev/tty cbreak min 1` directly in my console. It output `stty` not recognize `-F`. 
I make `-F` to `-f` in source code, and rebuild. Finally it is working! Sooooooo cool!
I will pull a request for this bug fix.

**Comment by nnao45** [comment]
@Lqlsoftware 
Yeeaaaaaaaaaaaaaaaahhhhhhhh!!! 😝
thanks,when receiving PR, check & merge & close this issue.
