### ISSUE TITLE
Get golang source file separate group by its function.

### ISSUE THREAD

**Issue by Lqlsoftware** [nnao45/dntk#7]
@nnao45 
Hi dude, emmmmm... I can see that you like to code in one go file, but it is too long for one file and we cannot find definition quickly or add function quickly. So can we separate the dntk.go file to some go file?

**Comment by nnao45** [comment]
@Lqlsoftware 
Hey dude.
Sorry for the late reply.

>So can we separate the dntk.go file to some go file?

I agree, nice idea.
Okay...how we recreate souce code dir😶

I think....
```
pkg/
 |
 |__dntk.go(package main)(only func main)
 |__cursor/
 |     |__cursor.go(package cursor)(func with cgo)
 |__prompt/
 |     |__prompt.go(package prompt)(func to print prompt)
 |__bc/
     |__bc.go(package bc)(func (l *line) calcBuffer() []byte and more )
```

umm...all refactoring this repo....
do you think?

**Comment by Lqlsoftware** [comment]
@nnao45 
Nice refactoring!
But I think package cursor is a subset of prompt, right? 
Emmmmm, I've tried refactoring but it looks not beautiful like yours.

**Comment by nnao45** [comment]
@Lplsoftware
cool!! I m grateful to you will.
and I'll try too.
